inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*.rb
    - spec/**/*

Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
