name: Cypress Tests (Edge)
on:
  push:
    branches-ignore:
      - '**' # temp disabled
jobs:
  edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test Docker Compose
        run: docker-compose up
        env:
          DOCKER_CLI_EXPERIMENTAL: endabled
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Configure
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          npm config set @dfe-digital:registry=https://npm.pkg.github.com
      - name: Run E2E Tests (Edge)
        uses: cypress-io/github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KNOWN_TEACHER_UUID: ff37bd17-42be-47ab-8141-2f5e3b7f2b7f
          API_TOKEN: fb5542df-50e7-4c05-a74e-4f2123f46554
          CYPRESS_BASE_URL: http://localhost:3000
          DOCKER_CLI_EXPERIMENTAL: endabled
        with:
          build: npx cypress info
          start: docker-compose up
          wait-on: "http://localhost:3000"
          # parallel: true
          # record: true
          # group: "E2E Testing Edge"
          browser: edge
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
